### ISSUE TITLE
Investigate Leaflet 1.0

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-plugin-map#22]
From a brief look, while switching to loading leaflet over https, it appears that something has changed with dragging as the behaviour appears to be different.

**Comment by WardCunningham** [comment]
I've built and tried this but don't notice any change with dragging. Where should I test?

**Comment by WardCunningham** [comment]
I do see fetches from unpkg.com using https but tile fetches from osm.org are http.

**Comment by paul90** [comment]
#21 is still using Leaflet 0.7(?), when I tried using 1.0.1 dragging the map didn't just drag the map content but also the map across the page. I see some issues in the Leaflet repo about event bubbling, so assume that it is related.

Requesting the map tiles over http should be alright, though it might be good to look at that as well.

**Comment by paul90** [comment]
Leaflet was updated in v0.3.5.
