### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-plugin-map#4]
There is some basic functionality that is currently missing from this plug-in:

1. It is not possible to drag a map to a different place within the view. Once created, if you want to move the map to a different place within the page you can't just drag it to where you want it.
1. It is not possible to place a marker on the map. The previous version had a static marker, but this was not moveable. 
1. It is not possible to create a new map item - map is not listed in the factory list.

Anything basic functionality missing? More advanced functionality required?

**Comment by WardCunningham** [comment]
There is work in progress that addresses these issues. The work by @clemsos and others will result in a pull request back to this repo. See https://github.com/clemsos/wiki-plugin-map/pull/7

**Comment by WardCunningham** [comment]
The features suggested in this issue have been coded and committed now pending a pull request from @clemsos.
